version: '3.7'
services:
    nginx:
        build: ./nginx
        ports:
            - 80:80
        volumes:
            - static_volume:/app/carbon_friendly/static
        depends_on:
            - django
        restart: "on-failure"
    django:
        build: .
        command: sh -c "python carbon_friendly_api/manage.py collectstatic &&
                        gunicorn carbon_friendly_api.wsgi:application --bind 0.0.0.0:8000 --chdir carbon_friendly_api"
        volumes:
            - .:/carbon_friendly_api:rw
            - static_volume:/app/carbon_friendly_api/static
        env_file:
            - env.list
        image: django
        expose:
            - 8000
        restart: "on-failure"
volumes:
  static_volume:
