# Generated by Django 3.2.4 on 2021-08-30 14:28

import uuid

from django.core.management import call_command
from django.db import migrations, models


def forward(apps, schema_editor):
    """Load resources JSON file."""
    call_command('loaddata', "resources.json", app_label='core') 


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=256)),
                ('group', models.CharField(max_length=64)),
                ('subgroup', models.CharField(max_length=64)),
                ('icon', models.CharField(max_length=64)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
        migrations.RunPython(forward),
    ]
